In [1]:
import numpy as np

In [2]:
# Using py list to make an array
array1 = np.array([1, 2, 4, 6, 9, 11, 99])
array1

array([ 1,  2,  4,  6,  9, 11, 99])

In [3]:
# ndarray means n dimension array
type(array1)

numpy.ndarray

In [4]:
array2 = np.array ([[4, 2, 7, 9], [36, 812, 22, 423], [296, 6, 49, 41]])
array2

array([[  4,   2,   7,   9],
       [ 36, 812,  22, 423],
       [296,   6,  49,  41]])

In [5]:
#shape(row, column)
array2.shape

(3, 4)

In [6]:
#size = row * column
array2.size

12

In [7]:
# full(a,b): repeating b a times
array3 = np.full(2,5)
array3

array([5, 5])

In [8]:
# same as np.full(6, 0)
array4 = np.zeros(6, dtype=int)
array4

array([0, 0, 0, 0, 0, 0])

In [9]:
# same as np.full(2, 1)
array5 = np.ones(2, dtype=int)
print(array5)
array5

[1 1]


array([1, 1])

In [10]:
# array with random values, using random function in random module
array6 = np.random.random(3)
array6

array([0.03394524, 0.8317134 , 0.23810655])

In [11]:
# arange works similar with range in py
# arange(x): 0 to x-1
# arange(x,y): x to y-1
# arange(x,y,z): values with the interval z from x to y-1
array7 = np.arange(6)
print(array7)
array8 = np.arange(2,7)
print(array8)
array9 = np.arange(1,100,6)
print(array9)

[0 1 2 3 4 5]
[2 3 4 5 6]
[ 1  7 13 19 25 31 37 43 49 55 61 67 73 79 85 91 97]
