In [1]:
#Boolean calculations
import numpy as np
array1 = np.arange(5,24)
array1 < 20

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False])

In [2]:
#np.where(boolean_array) will show the index of TRUE
array2 = array1 < 18
np.where(array2)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),)

In [3]:
#Can use the np.where as a filter as below
filter = np.array(array1 > 16)
array1[filter]

array([17, 18, 19, 20, 21, 22, 23])