In [1]:
#In Python, all values had to be applied one by one through a loop, but in numpy, it can be applied to the entire array.
import numpy as np
array1 = np.arange(10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
print(array1*10)
print(array1/2)
print(array1**2)
print(array1+1)
print(array1-33)
print(array1//3)

[ 0 10 20 30 40 50 60 70 80 90]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 0  1  4  9 16 25 36 49 64 81]
[ 1  2  3  4  5  6  7  8  9 10]
[-33 -32 -31 -30 -29 -28 -27 -26 -25 -24]
[0 0 0 1 1 1 2 2 2 3]


In [4]:
array2 = np.arange(20,30)
array1 + array2

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])